apiVersion: apps/v1
kind: Deployment
metadata: 
  name: task4-deply
spec:
  replicas: 3
  selector:
    matchExpression:
    - { key: env, operator: In, values: [ production ] }
  template:
    metadata:
      name: task4-pod
      labels:
        env: production 
    spec:
      containers:
      - name: mytask-con
        image: httpd
        volumeMounts:
        - mountPath: /var/www/html
          name: mypd

      volumes:
      - name: mypd
        persistentVolumeClaim:
          claimName: task4-pvc
