FROM centos:latest

RUN yum install java-1.8.0-openjdk -y
RUN yum install openssh-server -y
RUN echo "root:redhat123" | chpasswd
RUN ssh-keygen -A

RUN yum install curl -y
RUN yum install sudo -y
RUN url -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl


RUN chmod +x ./kubectl
RUN mv ./kubectl /usr/local/bin/
COPY client.key /root/
COPY client.crt /root/
COPY ca.crt /root/
RUN mkdir /root/.kube
COPY config /root/.kube/config
RUN mkdir /root/yaml
EXPOSE 22
CMD ["/usr/sbin/sshd","-D"]
